# Generated by Django 2.1.5 on 2020-01-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extrauserinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='orderitems',
            field=models.ManyToManyField(blank=True, related_name='orderitems', to='orders.Orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='orders.Category'),
        ),
    ]
