# Generated by Django 2.1.5 on 2020-01-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200122_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extrauserinfo',
        ),
    ]
